### PR TITLE
count breadcrumbs feature added

### PR DESCRIPTION
**Pull request by afbora**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Hello @afbora

Thank you for your contributing.
Could you please fix Phalcon 2.1.x issue by adding to the `.travis.yml` the `--ignore-platform-reqs` option:

``` yaml
- travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
```

For example:
https://github.com/phalcon/forum/blob/master/.travis.yml#L35

This issue related to the SemVer. Composer expects something like `2.1.0-rc.1`. But Phalcon does not follows SemVer and it version called `2.1.0r`

**Comment by afbora** [comment]
Added but 2 job failed :\

https://github.com/afbora/breadcrumbs/blob/master/.travis.yml#L21

**Comment by sergeyklay** [comment]
This need add to this PR. Just change this line https://github.com/phalcongelist/breadcrumbs/blob/c48a6737437e5da14697d4d14c1133c8551b9a07/.travis.yml#L21

**Comment by sergeyklay** [comment]
Bleh. Latest Codeception does not work with php 5.4

**Comment by sergeyklay** [comment]
We need exclude PHP 5.4 from building process. Could you please update `.travis.yml`?

**Comment by sergeyklay** [comment]
Thanks

**Comment by afbora** [comment]
Thanks for helping my contribute, i didnt use travis before :smile:

**Comment by afbora** [comment]
https://github.com/phalcongelist/breadcrumbs/blob/master/composer.json#L26

Now, should be `"php": ">= 5.5"` on `composer.json`?

**Comment by afbora** [comment]
https://github.com/phalcongelist/breadcrumbs/blob/1.2.x/composer.json#L26

I didnt see, you already changed :+1:

**Pull request merged**
